[package]
name = "rosm_pbf_reader"
version = "0.2.0"
authors = ["Zsolt Bölöny <bolony.zsolt@gmail.com>"]
edition = "2018"

[dependencies]
flate2 = "1.0"
quick-protobuf = "0.8"

[build-dependencies]
pb-rs = "0.9"

[dev-dependencies]
threadpool = "1.8"
