[package]
name = "rosm_pbf_reader"
version = "0.2.0"
authors = ["Zsolt Bölöny <bolony.zsolt@gmail.com>"]
edition = "2018"

[dependencies]
flate2 = "1.0"
quick-protobuf = { git = "https://github.com/tafia/quick-protobuf.git", rev = "4caf51c40405ae6b3740251bac9172103aa73465" }

[build-dependencies]
pb-rs = { git = "https://github.com/tafia/quick-protobuf.git", rev = "4caf51c40405ae6b3740251bac9172103aa73465" }

[dev-dependencies]
threadpool = "1.8"
