[package]
name = "rosm_pbf_reader"
version = "0.1.0"
authors = ["Zsolt Bölöny <bolony.zsolt@gmail.com>"]
edition = "2018"

[dependencies]
flate2 = "1.0"
quick-protobuf = "0.7.0"

[build-dependencies]
pb-rs = "0.9.0"
