[package]
name = "rosm_pbf_reader"
version = "0.1.0"
authors = ["Zsolt Bölöny <bolony.zsolt@gmail.com>"]
edition = "2018"

[dependencies]
quick-protobuf = "0.6.4"
flate2 = "0.2"

[build-dependencies]
pb-rs = "0.8.3"
