[package]
name = "rosm_pbf_reader"
version = "0.3.0"
authors = ["Zsolt Bölöny <bolony.zsolt@gmail.com>"]
edition = "2021"

[dependencies]
flate2 = { version = "1.0", optional = true }
prost = "0.10"

[features]
default = ["flate2"]

[build-dependencies]
prost-build = "0.10"

[dev-dependencies]
threadpool = "1.8"
